:- dynamic(palavra/1).

writefacts(Palavra):-
    open('palavras.pl',append,Out),
    string_concat('\npalavra(''', Palavra, String3),
    string_concat(String3, ''').', String4),
    write(Out, String4),
    close(Out).  


palavra('presunto').
palavra('sobre').
palavra('sul').
palavra('fio').
palavra('carrapato').
palavra('molde').
palavra('pulsar').
palavra('golfinho').
palavra('mola').
palavra('varejo').
palavra('hospital').
palavra('motel').
palavra('diario').
palavra('foto').
palavra('aderir'). 
palavra('teste').
palavra('surpresa').
palavra('flamenco').
palavra('laringe').
palavra('discar').
palavra('aperitivo').
palavra('cumprimentar').
palavra('anestesia').
palavra('bateria').
palavra('torre').
palavra('cesta').
palavra('aguaceiro').
palavra('motor').
palavra('dezembro').
palavra('pasta').
palavra('radiante').
palavra('mascarar').
palavra('computador').
palavra('dinheiro').
palavra('recipiente').
palavra('flutuador').
palavra('defesa').
palavra('trabalho').
palavra('fuga').
palavra('lugar').
palavra('magro').
palavra('concha').
palavra('sempre').
palavra('asno').
palavra('borboleta').
palavra('pia').
palavra('lago').
palavra('atual').
palavra('infantil').
palavra('data').
palavra('pilha').
palavra('cachos').
palavra('parente').
palavra('bater').
palavra('aposta').
palavra('oceano').
palavra('cadeado').
palavra('flores').
palavra('chuva').
palavra('boca').
palavra('temporada').
palavra('para').
palavra('de').
palavra('com').
palavra('eu').
palavra('tu').
palavra('topo').
palavra('subir').
palavra('radical').
palavra('flauta').
palavra('hipnotizar').
palavra('fechado').
palavra('conflito').
palavra('gordura').
palavra('nota').
palavra('gaiola').
palavra('selo').
palavra('liberdade').
palavra('pico').
palavra('manteiga').
palavra('custo').
palavra('carro').
palavra('futebol').
palavra('pulso').
palavra('filho').
palavra('cantou').
palavra('aparar').
palavra('limpo').
palavra('antena').
palavra('cliente').
palavra('corpo').
palavra('popular').
palavra('tela').
palavra('limpo').
palavra('teclado').
palavra('tijolo').
palavra('chifre').
palavra('caderno').
palavra('luz').
palavra('jubilado').
palavra('a').
palavra('ligeira').
palavra('raposa').
palavra('marrom').
palavra('saltou').
palavra('sobre').
palavra('o').
palavra('cachorro').
palavra('cansado').
palavra('testando').